name = "PSOGPU"
uuid = "ab63da0c-63b4-40fa-a3b7-d2cba5be6419"
authors = ["Utkarsh <rajpututkarsh530@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
